### ISSUE TITLE
clean and works: thank you!

### ISSUE THREAD

**Issue by MacKentoch** [mmazzarolo/react-native-beacons-android#10]
Your version suits better my needs (_and my way coding_).
### Thank you!

Now I can use beacons in iOS and in Android 👍 +1

**Comment by MacKentoch** [comment]
it is not an issue (as title says 😄 )

**Comment by mmazzarolo** [comment]
Hey! Thanks, glad to know it works! 👍 
Please keep me updated on any issue you find and feel free to send any PR/request!

**Comment by MacKentoch** [comment]
@mmazzarolo sure.

I'm preparing a _super simple project_ just for showing iOS and Android RN examples for playing with iBeacons.
I will give you link when I'm done so that it will be at least a 1st example to implement it with `react-native-beacons-android`.

Have a look at iOS version this [PR#44](https://github.com/frostney/react-native-ibeacon/pull/34) to help others like me

**Comment by mmazzarolo** [comment]
Nice!

Don't know if you're interested but here is a little helper I'm using for handling both `react-native-ibeacon` and `react-native-beacons-android`.  
It is exaggeratedly verbose and customized, I know, but I did it this way for simplifying my unit-testing and I didn't have time for creating an easier example 🙍

``` javascript
/* eslint-disable global-require */
import { DeviceEventEmitter, Platform } from 'react-native'
import Keys from '../config/keys'
import i18n from '../i18n'

const IS_ANDROID = Platform.OS === 'android'
let Beacons
if (IS_ANDROID) {
  Beacons = require('react-native-beacons-android')
} else {
  Beacons = require('react-native-ibeacon')
}

export const initializeBeaconsHandler = () => {
  if (IS_ANDROID) {
    Beacons.detectEstimotes()
  } else {
    Beacons.requestWhenInUseAuthorization()
  }
}

// MobX stuff, can be easily replaced with Redux/anything else
export const connectBeaconsEventsToStore = (museumsStore, beaconsStore) => {
  DeviceEventEmitter.addListener('beaconsDidRange', (obj) => {
    const { beacons } = obj
    beaconsStore.setBeaconsInRange(beacons)
  })
}

export const startRanging = async () => {
  try {
    if (IS_ANDROID) {
      const transmissionSupport = await Beacons.checkTransmissionSupported()
      if (transmissionSupport !== 'SUPPORTED') {
        const errorMessage = i18n.t(`ERROR_${transmissionSupport}`)
        throw new Error(errorMessage)
      }
      await Beacons.startRangingBeaconsInRegion(Keys.BEACONS_REGION_ID, Keys.BEACONS_UUID)
    } else {
      const region = { identifier: Keys.BEACONS_REGION_ID, uuid: Keys.BEACONS_UUID }
      Beacons.startRangingBeaconsInRegion(region)
    }
    return ({ result: 'success' })
  } catch (e) {
    console.log(e)
    return ({ error: e.message || 'Something bad happened' })
  }
}

export const stopRanging = () => {
  if (IS_ANDROID) {
    Beacons.stopRangingBeaconsInRegion()
  } else {
    const region = { identifier: Keys.BEACONS_REGION_ID, uuid: Keys.BEACONS_UUID }
    Beacons.stopRangingBeaconsInRegion(region)
  }
}
```

**Comment by MacKentoch** [comment]
Nice, thank you.

Nice idea: I guess I will make then **another example — more advanced and better for production —** later using this (_I agree with you and I will already use it on my projects_).

I'd like the 1st example to be as easy as possible not to scary newcomers 😄 (_it takes time for me to make it clear since I have habbits that are not for newcomers_).

**Comment by MacKentoch** [comment]
1st example:  [simple project](https://github.com/MacKentoch/reactNativeBeaconExample).

Thank you @mmazzarolo !
Hope we will see even more beacon apps or new ideas from beacons.

**Comment by mmazzarolo** [comment]
@MacKentoch: awesome man, added to the README 💇

**Comment by mint3000** [comment]
@mmazzarolo is it possible to range for multiple beacons? Something like this:

```
_.forEach(portraitData, (portrait) => {
Beacons.startRangingBeaconsInRegion('REGION1', portrait.uuid)
      .then(() => console.log(`Beacons ranging started succesfully`))
      .catch(error => console.log(`Beacons ranging not started, error: ${error}`));
});
```

When I run this, it seems to only monitor the last UUID in portraitData. Any ideas?

**Comment by mmazzarolo** [comment]
@mint3000, let's discuss it on #12 👍
