### ISSUE TITLE
Ranging for multiple beacons

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-beacons-android#12]
From #10, @mint3000 :

> is it possible to range for multiple beacons? Something like this:
> 
> ```
> _.forEach(portraitData, (portrait) => {
> Beacons.startRangingBeaconsInRegion('REGION1', portrait.uuid)
>       .then(() => console.log(`Beacons ranging started succesfully`))
>       .catch(error => console.log(`Beacons ranging not started, error: ${error}`));
> });
> ```
> 
> When I run this, it seems to only monitor the last UUID in portraitData. Any ideas?

Nice question.  
Currently the library handles only one ranging sessions (and the altBeacon library used internally [doesn't seem to support multiple monitoring/ranging](https://github.com/AltBeacon/android-beacon-library/issues/170)).  
Does anybody know if `react-native-ibeacon` allows multiple ranging?  

Interesting discussions:
[Multiple Monitoring, Ranging Notifiers](https://github.com/AltBeacon/android-beacon-library/issues/170)

**Comment by gpEscrivo** [comment]
I can confirm that `react-native-ibeacon` is able to range for multiple regions. 

_`BeaconList.js`_

```
  renderBeacons (data) {
    beacons = [];

    for (let i = 0; i < data.length; i++) {
      beacons.push(
        <Beacon
          key = {i}
          identifier = { data[i].name }
          uuid = { data[i].uuid }
          description = { data[i].description }
          killSelf = { !this.props.shouldDo }
        />
      )
    }

    return beacons;
  }
```

_`Beacon.ios.js`_

```
...

  updateRegion(region){
    Beacons.startRangingBeaconsInRegion(region);
    this._subscription = DeviceEventEmitter.addListener(
      'beaconsDidRange',
      this.beaconsDidRange.bind(this)
    );
  }

...
```

Working :)

_`Beacon.android.js`_

```
...

  updateRegion(identifier, uuid){
    Beacons.startRangingBeaconsInRegion(identifier, uuid)
      .catch(error => console.log(`Beacons ranging not started, error: ${error}`));

    this._subscription = DeviceEventEmitter.addListener(
      'beaconsDidRange',
      this.beaconsDidRange.bind(this)
    );
  }

...
```

Only looks for last in array :(

**Comment by mmazzarolo** [comment]
@mint3000
Hey, I just released a new beta version of this library on npm: `react-native-beacons-android 2.0.0-beta.1`.  
In this new version you should be able to range for multiple beacons, just remember to use a different identifier (from the example above: `'REGION1'`) for each ranging attempt.  

Let me know if it works... it is still in beta 👍

**Comment by mmazzarolo** [comment]
Feedbacks on this feature are welcome [here](https://github.com/mmazzarolo/react-native-beacons-android/issues/20).
