### ISSUE TITLE
Background Monitoring

### ISSUE THREAD

**Issue by OFranke** [mmazzarolo/react-native-beacons-android#13]
Hi,

I am currently experimenting with your lib (thanks a lot! I was able to receive the first signals within minutes!). 
Right now I am wondering, how to use the background monitoring. What I want to do is the following:
1. receive the monitoring signal
2. send the signal to my backend API / alternative: create a local notification that is being displayed

Could you point me to the right direction here? Thanks a lot!

**Comment by mmazzarolo** [comment]
Hello @OFranke!  

1) Monitoring should work in a similiar way of ranging:  

``` javascript
import { DeviceEventEmitter } from 'react-native'
import Beacons from 'react-native-beacons-android'

// Tells the library to detect iBeacons
Beacons.detectIBeacons()

// Start detecting all iBeacons in the nearby
Beacons.startRangingBeaconsInRegion('YOUR REGION')
  .then(() => console.log(`Beacons monitoring started succesfully!`)
  .catch(error => console.log(`Beacons monitoring not started, error: ${error}`)

// Print a log when you enter a region
DeviceEventEmitter.addListener('regionDidEnter', (region) => {
  console.log('Entered new beacons region!', region)
})
```

2) If you need to handle the signal the right place to look for is the `regionDidEnter` and `regionDidExit` callbacks:

``` javascript
// Handle the info when you enter a region
DeviceEventEmitter.addListener('regionDidEnter', (region) => {
  yourBackendService.sendInfo('regionDidEnter', region) // Your custom logic for sending the message to backend
  yourNotificationModel.showNotification('You just entered a beacon region!') // Your custom logic for showing a notification
})
```

Please keep in mind that beacons monitoring is not tested too much, so any help and feedback is really appreciated 👍 

P.S.: For handling the notifications I suggest you to take a look [here](https://js.coach/react-native?search=notification).

**Comment by OFranke** [comment]
Thanks @mmazzarolo for the fast response.

The way I understand background monitoring is: I will get a signal, even when the app is closed (killed, not running in the background). Is that right?

So I wonder how the Beacons.startMonitoringForRegion() function can be executed, if my app has never been opened by the user. Do I need to start the monitoring somehow in native code to make that work?

I think I have a little lack of understanding here. I'll give you as much feedback as possible, once I get to the point.

**Comment by mmazzarolo** [comment]
Sadly background monitoring currently doesn't work when the app is killed (it works in background though).  
I already planned to add a support to it but I'm not even close to a preview: I only know I should implement it using an android service but I still haven't looked into services on react-native.
😞

**Comment by OFranke** [comment]
Ah okay, If I can somehow manage to implement that, I'll post it here, but for the moment I got enough other tasks open. 
I've read some nice articles here: 
http://developer.estimote.com/android/tutorial/part-2-background-monitoring/#key-takeaways 
and here (see comments from Nikolas LeBlanc):
https://community.estimote.com/hc/en-us/articles/201491176-How-Monitoring-in-the-background-works-on-Android-

Maybe that's helpful :)

Thanks!

**Comment by mmazzarolo** [comment]
Thank you 👍

**Comment by oferRounds** [comment]
@OFranke have you managed to make the monitoring work also when the app is killed? (both iOS and Android)
