### ISSUE TITLE
Error: cannot read addParse of undefined

### ISSUE THREAD

**Issue by alessandro-bottamedi** [mmazzarolo/react-native-beacons-android#14]
When i execute Beacons.detectIBeacons() or detectCustomLayout i riceve this errors.

RN 0.29
android 5.1

**Comment by mmazzarolo** [comment]
Hi there!
Can you provide the snippet of code?

Did you install the module using `rnpm`? 
I think the error might be related to using `rnpm link` on React-Native 0.29.  

Give it a check, your `/android/src/main/java/...yourpackage/MainActivity.java` should be like this:

``` java
package it.yourpackage;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "YourAppName";
    }
}
```

And your `/android/src/main/java/...yourpackage/MainApplication.java` should be like this:

``` java
package it.yourpackage;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import com.mmazzarolo.beaconsandroid.BeaconsAndroidPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          // ...all your other packages
          new BeaconsAndroidPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}

```

**Comment by mmazzarolo** [comment]
Instead of doing the above procedure you can also try to just run `react-native link`, it should work! 👍 
Let me know if it works for you so that I can update the README.md!

**Comment by alessandro-bottamedi** [comment]
Thanks resolved, rnpm put these lines:
`import com.mmazzarolo.beaconsandroid.BeaconsAndroidPackage;` 
and
`new BeaconsAndroidPackage()`
in MainActivity.java

I copy these lines in MainApplication.java and all works, thanks!

**Comment by mmazzarolo** [comment]
Yep, that's because since RN0.29 `rnpm` is integrated in `react-native` itself... `react-native link` should work correctly 👍

**Comment by affibox** [comment]
Quote:"Thanks resolved, rnpm put these lines:
import com.mmazzarolo.beaconsandroid.BeaconsAndroidPackage; 
and
new BeaconsAndroidPackage()
in MainActivity.java

I copy these lines in MainApplication.java and all works, thanks!"

I try this and didn't work.
