### ISSUE TITLE
The BeaconManager is not bound to the service. Call beaconManager.bind(BeaconConsumer consumer) and wait for a callback to onBeaconServiceConnect()

### ISSUE THREAD

**Issue by s2t2** [mmazzarolo/react-native-beacons-android#16]
Hi, I'm running into the error `The BeaconManager is not bound to the service. Call beaconManager.bind(BeaconConsumer consumer) and wait for a callback to onBeaconServiceConnect()` ~~when I navigate back to this page from another page~~ EDIT: **when i navigate away from the page, then back again, then away again for the second time**, and I'm not sure why. 

I bet its probably due to my limited understanding of how to use the library correctly, and not a bug, but I was hoping you still might be able to provide some insight into how to fix it or how to configure my code properly. 

See below for the pertinent details of my component, and thank you for you time.

``` js
import React from 'react';
import {Text, DeviceEventEmitter} from 'react-native';
import Beacons from 'react-native-beacons-android';

const HomePage = React.createClass({
  getInitialState: function(){
    return {detections:[]};
  },

  componentWillMount: function(){
    Beacons.detectIBeacons();
    Beacons.startRangingBeaconsInRegion('REGION1')
      .then(function(){  console.log("Beacon Ranging OK")  })
      .catch(function(error){  console.log("Beacon Ranging ERR", error)  });
  },

  componentDidMount: function(){
    this.beaconsDidRange = DeviceEventEmitter.addListener("beaconsDidRange", this.emitBeaconData);
  },

  componentWillUnmount: function(){
    this.beaconsDidRange = null;
  },

  render: function(){
    return (
       <Text>Hello</Text>
    );
  },

  emitBeaconData: function(data){
    // COLLECT DETECTION RESULTS INTO STATE UNTIL IT REACHES A CRITICAL MASS, THEN NAVIGATE TO ANOTHER PAGE PASSING THE COLLECTION AS PROPS
    var detections = this.state.detections;
    if (detections.length >= 10) {
      this.setState({detections:[]})
      this.stopDetectingBeacons();

      this.goIndex(detections);
    } else {
      this.setState({detections: this.state.detections.concat(data.beacons)});
    };
  },

  stopDetectingBeacons(){
    Beacons.stopRangingBeaconsInRegion('REGION1')
      .then(function(){  console.log("Beacon Ranging Stopped OK")  })
      .catch(function(error){  console.log("Beacon Ranging Stopped With ERR", error)  });
  },

  // FYI: using Navigator from react-native
  goIndex(results){
    this.props.navigator.push({
      name: 'Index',
      passProps: {
        results: results
      }
    })
  }
});

module.exports = HomePage;
```

EDIT: logs show the error happening after the OK, which is somewhat confusing.

``` sh
07-28 11:45:10.168 18549 18795 I ReactNativeJS: INDEX DID MOUNT
07-28 11:45:10.169 18549 18795 I ReactNativeJS: Beacon Ranging Stopped OK
07-28 11:45:10.171 18549 18795 I ReactNativeJS: 'Beacon Ranging Stopped With ERR', 'The BeaconManager is not bound to the service.  Call beaconManager.bind(BeaconConsumer consumer) and wait for a callback to onBeaconServiceConnect()'
```

**Comment by mmazzarolo** [comment]
Hi! I'm on holiday right now, I'll take a look at it in the weekend :)

**Comment by s2t2** [comment]
Thanks, I think I've at least diagnosed the issue, which is that react-native's `Navigator` [does not trigger `componentWillUnmount`](https://github.com/facebook/react-native/issues/1731). So the event listener never gets removed. Then when navigating back to the page, the page gets mounted again and another event listener gets added, which results in duplicate logging and duplicate attempts to stop ranging. The first attempt to stop ranging results in OK, but the second attempt results in the error in question.

Right now I just need to figure out how to trigger a component unmount or move the `startRangingBeaconsInRegion` and `stopRangingBeaconsInRegion` functions to work-around the issue.

I will post a solution when I find one for future googlers, but feel free to close this issue, as it is more related to the react-native Navigator than this library.

Thanks for your attention and for this awesome library!

**Comment by mmazzarolo** [comment]
On mobile, sorry for typos :p
It has been ages since I used the classic navigator (I'm using the experimental one) but if I remember correctly you should just play with the `onDidFocus` trigger (for example you can stop the monitoring on route push and start it on route focus).  Let me know and have a nice day man.

**Comment by mmazzarolo** [comment]
Also, I'll close the issue but feel free to re-open of needed!

**Comment by s2t2** [comment]
FYI for googlers, `navigator.push` does not trigger a component's `componentWillUnmount`, but a solution to my question involves using either`navigator.replace` or `navigator.resetTo`, which both do trigger `componentWillUnmount`.

See: https://facebook.github.io/react-native/docs/navigator.html#methods
