### ISSUE TITLE
Detect if beacon ranging is on or off

### ISSUE THREAD

**Issue by s2t2** [mmazzarolo/react-native-beacons-android#17]
I'm trying to conditionally trigger `startRangingBeaconsInRegion` only if it is not currently ranging, to avoid the device event emitter listening and logging two different ranging attempts.

Is it possible to detect whether or not ranging is on or off (for a given region)?

**Comment by mmazzarolo** [comment]
Hey @s2t2, sorry if I've been late but I just released a new beta version of this library on npm: `react-native-beacons-android 2.0.0-beta.1`.  
In this new version you should be able to achieve what you're asking by calling `Beacons.beaconsAndroid.getMonitoredRegions()`.  
The `getMonitoredRegions` function returns a promise that resolves an array of the currently monitored regions. If the returned array has a length of 0 then you're not ranging.
Example:

``` javascript
const rangedRegions = await Beacons.getRangedRegions()
const isRanging = rangedRegions.length > 0
```

Let me know if it works... it is still in beta 👍

**Comment by s2t2** [comment]
Sounds good!

**Comment by mmazzarolo** [comment]
@s2t2, your feedback would be appreciated [here](https://github.com/mmazzarolo/react-native-beacons-android/issues/20). Thank you ;)
