### ISSUE TITLE
When trying to use "Beacons.detectIBeacons()" getting error undefined is not an object (evaluating 'beaconsAndroid.addParser')

### ISSUE THREAD

**Issue by SonalRewri** [mmazzarolo/react-native-beacons-android#18]
I checked the link also - 
react-native link
rnpm-install info Android module react-native-beacons-android is already linked

Any other thing i can check.

**Comment by mmazzarolo** [comment]
Why did you already closed the issue? 😄  
However I'm feeling it must be related to #14, did you already check it?  
What version of React-Native are you using?

**Comment by mmazzarolo** [comment]
I just tested it, if you're on RN >= 0.30 you must link the project using `react-native link` and it will link `react-native-android-beacons` correctly.

I'm closing the issue but feel free to comment here 👍

**Comment by SonalRewri** [comment]
Thanks for the reply, the issue got solved.
The RN version is react-native: 0.31.0.

I am facing another problem in detecting the beacons, the error is - "CycledLeScanner: No Bluetooth adapter.  beaconService cannot scan.." Any help is greatly appreciated. I am using Estimote beacons.

I am new one is RN and android development.

**Comment by mmazzarolo** [comment]
No worries.
That error sounds weird, are you using an emulator/virtual device?

**Comment by SonalRewri** [comment]
Yes I am using Android emulator .
Is it something related to this. Because when I am using my phone android 4.3 then on real device it's giving me error that batchedBridge is not bundled.

**Comment by affibox** [comment]
C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing\node_modules\react-native\Libraries\JavaScript…:61 Cannot read property 'addParser' of undefined

**Comment by olegdizus** [comment]
Have same error

**Comment by mmazzarolo** [comment]
Please follow [these steps](https://github.com/mmazzarolo/react-native-beacons-android/issues/19) and let me know the results 👍

**Comment by olegdizus** [comment]
I just added 

```
import com.mmazzarolo.beaconsandroid.BeaconsAndroidPackage;
```

and

```
 new BeaconsAndroidPackage()
```

to my MainApplication.java and it solved issue. Reinstalling or using react-native link did not help.

**Comment by mmazzarolo** [comment]
@olegdizus On which version of React-Native?  
It worked for me on both RN0.30 and RN0.31

**Comment by olegdizus** [comment]
@mmazzarolo react-native 0.29.0

**Comment by mmazzarolo** [comment]
Ah, that version seems to have some problem with linking...

**Comment by olegdizus** [comment]
At RN 0.31.0 linking works pretty well. Thanks for help!

**Comment by mmazzarolo** [comment]
No worries, have fun 👍
