### ISSUE TITLE
Feedback on version 2.0.0-beta.3

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-beacons-android#20]
Hello there, 
last week I released version `2.0.0-beta.3`, anyone available for testing it? 
Feedback are welcome 😄   

New features:
- Code cleanup on the Java side: it is a lot easier to implement new features now
- Added `removeParser(parser: String)` method for removing a specific parser
- Added `setBackgroundScanPeriod(period: int)`, `setBackgroundBetweenScanPeriod(period: int)`, `setForegroundScanPeriod(period: int)`, `setForegroundBetweenScanPeriod(period: int)` for handling scan polling, you can find the documentation [here](https://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/BeaconManager.html)
- You can scan for multiple region at the same time now, just remember to supply a different `regionId` for each call to `startMonitoringForRegion(regionId: String)` and `startRangingBeaconsInRegion(regionId: String)`
- Following the bullet point above: you must supply the correct `regionId` to `stopMonitoringForRegion(regionId: String)` and `stopRangingBeaconsInRegion(regionId: String)` for stopping the scan
- Added `getMonitoredRegions()` and `getRangedRegions()` that returns a promise resolving in an array of the currently monitored/ranged regions

Waiting for some feedbacks before updating the README.md and before officializing the release.

**Comment by fkattan** [comment]
Hi, 

Thanks for this component;  It's working fine on a non-production app. One thing I noticed is that it lets you monitor multiple times the same region; I think it should disregard silently any attempt to start monitoring a region that's already being monitored.  

I modified startMonitoring: 

`@ReactMethod
    public void startMonitoring(String regionId, String beaconUuid, Callback resolve, Callback reject) {

```
    Log.d(LOG_TAG, "startMonitoring, monitoringRegionId: " + regionId + ", monitoringBeaconUuid: " + beaconUuid);

    boolean isFound = false;
    for (Region region: mBeaconManager.getMonitoredRegions()) {
        if(region.getUniqueId().equalsIgnoreCase(regionId)) {
          isFound = true;
          break;
        }
    }

    if (isFound == true) {
      resolve.invoke();
      return;
    }

    try {
        Region region = createRegion(regionId, beaconUuid);
        mBeaconManager.startMonitoringBeaconsInRegion(region);
        resolve.invoke();
    } catch (Exception e) {
        Log.e(LOG_TAG, "startMonitoring, error: ", e);
        reject.invoke(e.getMessage());
    }
}`
```

**Comment by mmazzarolo** [comment]
Hey @fkattan! Happy that you're using this library, are you on `2.0.0`?  
You exposed an interesting thing and I agree, it shouldn't allow you to monitor the same region more than once.  
I'm pinning it as one of the next thing I'll take a look into.

**Comment by fkattan** [comment]
Yes. 2.0.0. I just posted some code to do just that.

**Comment by mmazzarolo** [comment]
Yep, I was already thinking about a similiar solution.  
I'll add it and probably release it tomorrow.  
Thanks again for the feedback and the code :+1:

**Comment by mmazzarolo** [comment]
@fkattan sorry, I can't add the feature this week... may you send a PR for it?
