### ISSUE TITLE
Beacon's prop of proximity incorrect.

### ISSUE THREAD

**Issue by hellowupeng** [mmazzarolo/react-native-beacons-android#21]
Hello
I'm using Beacon library with this one and a iOS library.
 First of all, thanks for your library.
 Recent I found when I scan beacons with a iPhone and Android phone, the prop of proximity of result from android phone always show 'near' whenever I change the distance from beacon, but the iPhone result is normal.
 Have you know this problem? or only happened to me, and any way to fix it.

**Comment by mmazzarolo** [comment]
Hello @hellowupeng,
what version of `react-native` and `react-native-android-beacons` are you using?

**Comment by hellowupeng** [comment]
version 1.3.1 @mmazzarolo

**Comment by mmazzarolo** [comment]
#6 might be interesting/related.
Seems weird...
Do the beacons always appear as "near" even if you get really, really far from them (for example when you're almost losing the signal)?

**Comment by hellowupeng** [comment]
@mmazzarolo I made a test with my partner just a moment ago. We found the prop of proximity of your library only return 'immediate' and 'near', but in iOS it return 'immediate', 'near', 'far', 'unknown'.

**Comment by mmazzarolo** [comment]
That's interesting, I'm using only the `immediate` and `near` info, I never checked for `far` but it should work too according to the [this](https://www.pubnub.com/blog/2015-04-15-build-android-beacon-ibeacon-detector/).  
It may be related to the type of your beacons.  
I can't work on it this week but in the meanwhile you can tweak the [`getProximity` method](https://github.com/mmazzarolo/react-native-beacons-android/blob/7040d9ab7791828926072b5e39d84bf35840211f/android/src/main/java/com/mmazzarolo/beaconsandroid/BeaconsAndroidModule.java#L266-L274) to better suit your needs (should't be too hard even without any Java background).  

#### Example on how to tweak the proximity method
1. Open to `yourapp/node_modules/react-native-beacons-android/src/main/java/com/mmazzarolo/beaconsandroid/BeaconsAndroidModule.java`.
2. Try changing `distance < 3` to `distance < 2` in the `getProximity`method.
3. Re-run you Android app with `react-native run-android` (and maybe reset you server too).

#### Optional: Loggin the distance parameter

Add the following line as the first line of the `getProximity` method (just before the `if`):   

``` java
Log.d(LOG_TAG, "getProximity, distance: " + distance.toString());
```

In this way the `distance`parameter will be logged to the console and you can see it with the following command in the terminal: `adb logcat | grep 'BeaconsAndroid'`

## 

Don't hesitate to comment here if you need further help.  
If you can find a sweetspot of the proximity I can push a new version next week (and maybe create a call to get directly the distance parameter).

**Comment by hellowupeng** [comment]
OK, thanks for your helping, I'll have a try.

**Comment by mmazzarolo** [comment]
@hellowupeng, did you get a chance to take a look at it?

**Comment by mmazzarolo** [comment]
@hellowupeng 😢
