### ISSUE TITLE
Detect beacons even when app is terminated

### ISSUE THREAD

**Issue by affibox** [mmazzarolo/react-native-beacons-android#26]
Is it possible to detect beacons even when the apps was terminated?

I need to implement this on a app and I need some help.

**Comment by ghost** [comment]
+1 please

**Comment by ank-khandelwal** [comment]
+1

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-beacons-android/issues/31

**Comment by Najeisleem** [comment]
there is any update on this issue ?

**Comment by mmazzarolo** [comment]
Sorry @Najeisleem , this library is not actively maintained anymore.

**Comment by Najeisleem** [comment]
Also the beacon manager library

**Comment by Najeisleem** [comment]
> Sorry @Najeisleem , this library is not actively maintained anymore.

dear @mmazzarolo 
what about MacKentoch/react-native-beacons-manager library? its same ?
