### ISSUE TITLE
Question about startRangingBeaconsInRegion and his eventListener

### ISSUE THREAD

**Issue by wcastand** [mmazzarolo/react-native-beacons-android#3]
Hi,

I would like to know if it's possible to fire this event (`beaconsDidRange`) even when beacons array is empty.

Right now, there is no way for me to update my list of beacons.
I need to know if a beacon is in range and update my list item to active or not, but when there is no beacon the event is not fired and i can't update my beacon list. :/

And i would like to avoid making a `startMonitoringForRegion` for every beacons in my list. :/

If you have a better solution, i would be really happy if you could explain it to me :)

**Comment by mmazzarolo** [comment]
Hello there,
you are totally right, I was already planning on doing something like this.  
After [this commit](https://github.com/mmazzarolo/react-native-beacons-android/commit/e22b1a1becfaed4334c9f70393973e7ec53e5dd5) the event should be triggered even if the beacons array is empty.

**Comment by wcastand** [comment]
Do you have an idea of when this is going to be pushed ? :)
Do you think it's possible to choose the format of the id sent by the event ? ( Hex or UUID )

And if it's possible to have the same info as `react-native-ibeacon` in the data that sent back the event beaconsDidRange.

```
    // data.region - The current region 
    // data.region.identifier 
    // data.region.uuid 

    // data.beacons - Array of all beacons inside a region 
    //  in the following structure: 
    //    .uuid 
    //    .major - The major version of a beacon 
    //    .minor - The minor version of a beacon 
    //    .rssi - Signal strength: RSSI value (between -100 and 0) 
    //    .proximity - Proximity value, can either be "unknown", "far", "near" or "immediate" 
    //    .accuracy - The accuracy of a beacon 
```

**Comment by mmazzarolo** [comment]
> Do you have an idea of when this is going to be pushed ? :)

Done :)

> Do you think it's possible to choose the format of the id sent by the event ? ( Hex or UUID )
> And if it's possible to have the same info as react-native-ibeacon in the data that sent back the event beaconsDidRange.

I'll take a look at it as soon as I can ;)

**Comment by wcastand** [comment]
Thank for your feedback and reactivity. That's awesome !! :)

**Comment by mmazzarolo** [comment]
No worries, I'm using this module in production, I'd love to keep it updated (and maybe merge it with `react-native-ibeacons` in the future).  
Issues posts and pull requests are welcome!

P.S.: I splitted your suggestions in two more issues: #4, #5
