### ISSUE TITLE
Beacons duplication

### ISSUE THREAD

**Issue by affibox** [mmazzarolo/react-native-beacons-android#30]
Heads up, the detected beacons are getting duplicated on the backend. 

10-28 11:10:11.720 19437-19478/com.ruralking I/ReactNativeJS: 'Entered new beacons region!', { uuid: 'MyBeacons' }
10-28 11:10:11.740 19437-19478/com.ruralking I/ReactNativeJS: Beacons ranging started succesfully!
10-28 11:10:12.150 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:12.150 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2906406130234607
10-28 11:10:12.150 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2906406130234607
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2906406130234607
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2906406130234607
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:12.160 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2906406130234607
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:13.320 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 22224
10-28 11:10:14.610 19437-19478/com.ruralking I/ReactNativeJS: 'Found beacons 1!', 1.2138722464362082

As you can see is the same beacon but it keeps duplicating when starting detection or turning on the beacon. 

I know the owner of this modules is always busy so if anyone has an idea of why this is going on please send me a message. I have a soft launch this next week and time is not an option.

**Comment by mmazzarolo** [comment]
FYI: I can't keep up with it, I'm trying to move this repo to https://github.com/react-native-community, hope they can help.
https://twitter.com/mazzarolomatteo/status/792026320385499137

**Comment by affibox** [comment]
For everyone out there using this module. This errors is happening because of the DeviceEventEmitter. 

Everytime you restart you app after closing it using android back button, it adds a new event listener to the device. This causes duplication errors.

A fix will be to create a variable ike this '''var d = DeviceEventEmitter()''' and after finishing the detection remove the listener like this '''d.remove()'''

This clears the DeviceEventEmitter and also duplication errors.
@mmazzarolo
