### ISSUE TITLE
How to detect iBeacons on array regions?

### ISSUE THREAD

**Issue by longtruongagn003** [mmazzarolo/react-native-beacons-android#37]
### Version
1.0.1

### Platform
Android

### OS version

 android 7.0...

###Actual behavior
I have a array regions:
const regions =[ 
{
    identifier: 'Estimotes_1',
    uuid: 'uuid_1'
},
{
    identifier: 'Estimotes_2',
    uuid: 'uuid_2'
},
{
    identifier: 'Estimotes_3',
    uuid: 'uuid_3'
},
]

How to detect iBeacons on array regions?
I tried but not work.
Beacons.startRangingBeaconsInRegion(regions[0]);
Beacons.startRangingBeaconsInRegion(regions[1]);
Beacons.startRangingBeaconsInRegion(regions[2]);

**Comment by mmazzarolo** [comment]
Sorry @longpro1601  , this library is not actively maintained anymore.
