### ISSUE TITLE
Use the same standard of react-native-ibeacons for the ranging output events

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-beacons-android#5]
From #3

**Comment by mmazzarolo** [comment]
@wcastand: can you provide me an example of the output of a ranging event of `react-native-ibeacons`?

**Comment by mmazzarolo** [comment]
I published a new version on npm (1.1.2) and I'm testing it just right now.  
Ranging output from `react-native-beacons-android`:

``` javascript
{
  region: {
    identifier: String,
    uuid: String
  },
  beacons: [
    {
       uuid: String, 
       major: Number, 
       minor: Number, 
       rssi: Number, 
       distance: Number // Unavailable on iOS
    }
  ]
}
```

Ranging output from `react-native-ibeacons`:

``` javascript
{
  region: {
    identifier: String,
    uuid: String
  },
  beacons: [
    {
       uuid: String, 
       major: Number, 
       minor: Number, 
       rssi: Number, 
       proximity: String, // It seems to be unavailable on Android
       accuracy: Number // It seems to be unavailable on Android
    }
  ]
}
```

**Comment by wcastand** [comment]
Thanks, i'm actually quite sad, because i'm suppose to based my app on the proximity :'(

You are using AltBeacon SDK. Did you look to SDK like Estimote ?

**Comment by mmazzarolo** [comment]
The Estimote SDK seems to be much less flexible then the AltBeacon SDK (correct me if I'm wrong).  
But! 
From my little knowledge the proximity info on iOS is a calculation on signal strength and accuracy, so you might use directly the `distance` field of the android version and associate some ranges to "near", "far" etc...  
Also, If you're able to find a distance - proximity conversion I'll gladly add the `proximity` info directly in the beacons response :)

**Comment by mmazzarolo** [comment]
Added proximity (might need some tuning).

Ranging output from `react-native-beacons-android`:

``` javascript
{
  region: {
    identifier: String,
    uuid: String
  },
  beacons: [
    {
       uuid: String, 
       major: Number, 
       minor: Number, 
       rssi: Number, 
       proximity: Number, 
       distance: Number // Unavailable on iOS
    }
  ]
}
```

Ranging output from `react-native-ibeacons`:

``` javascript
{
  region: {
    identifier: String,
    uuid: String
  },
  beacons: [
    {
       uuid: String, 
       major: Number, 
       minor: Number, 
       rssi: Number, 
       proximity: String, // It seems to be unavailable on Android
       accuracy: Number // It seems to be unavailable on Android
    }
  ]
}
```
