### ISSUE TITLE
Add the proximity info on ranging response

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-beacons-android#6]
From #5.

Some useful stuff:
- [StackOverflow: estimating-distance-to-ibeacon-on-ios](http://stackoverflow.com/questions/23392665/estimating-distance-to-ibeacon-on-ios)
- [StackOverflow: understanding-ibeacon-distancing](http://stackoverflow.com/questions/20416218/understanding-ibeacon-distancing)
- [StackOverflow: measure-distance-to-ibeacon-from-android-device](http://stackoverflow.com/questions/25483254/measure-distance-to-ibeacon-from-android-device)

**Comment by mmazzarolo** [comment]
Gonna implement [this](https://www.pubnub.com/blog/2015-04-15-build-android-beacon-ibeacon-detector/) in a minute.

**Comment by mmazzarolo** [comment]
Landed on 1.1.5, might need some tuning.

**Comment by wcastand** [comment]
hi,
I actually test react-native-ibeacon on IOS and this one on android. 
I have access to and estimote beacons.
and the result from both app are really different.

With my phone next to each other and the beacons 5meter away approximately, i get this result : 

```
//IOS:
[ { major: 32404,
    minor: 62922,
    uuid: 'B9407F30-F5F8-466E-AFF9-25556B57FE6D',
    accuracy: 10.83739327988672,
    rssi: -95,
    proximity: 'far' } ]
```

```
//ANDROID
distance: 1.1567290440348383
major: 32404
minor: 62922
proximity: "Near"
rssi: -80
uuid: "b9407f30-f5f8-466e-aff9-25556b57fe6d"
```

Do you know if we can use the same SDK on IOS and Android in order to have the same result, or at least something similar. :)

**Comment by mmazzarolo** [comment]
> Do you know if we can use the same SDK on IOS and Android in order to have the same result, or at least something similar. :)  

I'll do some research on the Estimote SDK, but in my opinion this library should continue using the Alt Beacons SDK since it supports almost every kind of beacons, [Estimote included](https://forums.estimote.com/t/estimote-beacons-not-detected-with-altbeacon-library/3129).
I also still need to do a lot of testing on aligning the results of this library with the iBeacons one (hope to do them this week).   

However please keep in mind that the result will never be the same because it is strictly tied to the Android device and its specs (you can have different result even comparing two Android devices).  

Regarding your test, the only two info you need to compare are `rssi` and `proximity`.
The `rssi` one shows the signal strength, the `proximity` one is an estimation of proximity that **is calculated differently** in iOS and Android. Take a look at the links in my first post for more info.  
If you have any suggestion on how to tweak the proximity value don't hesitate and send a pull request/write a post here :)

P.S.: The `distance` parameter on Android seems strange... make sure to wait at lease 20/30 seconds before taking notes of the parameter because that result is "smoothed" and require some time to settle :)

**Comment by mmazzarolo** [comment]
I'm closing, feel free to re-open if needed!
