### ISSUE TITLE
major and minor values are null in regionDidEnter, and regionDidExit

### ISSUE THREAD

**Issue by RezaRahmati** [mmazzarolo/react-native-beacons-android#7]
Hello

I am trying to use monitoring api, 
First of all I only would receive the regionDidExit event, so we found that it seems there is typo in line 131 of BeaconAndroidModule.java (both of the events are regionDidExit), so I changed that locally, now I get both events, but the problem is minor and major are empty.
I am calling the api as this

```
Beacons.startMonitoringForRegion('region2','523d3db0-0038-4cb4-b2b2-7d518adab463')
      .then(() => console.log(`iBeacon Beacons monitoring started succesfully`))
      .catch(error => console.log(`iBeacon Beacons monitoring not started, error: ${error}`));
```

and this

```
Beacons.startMonitoringForRegion('region2')
      .then(() => console.log(`iBeacon Beacons monitoring started succesfully`))
      .catch(error => console.log(`iBeacon Beacons monitoring not started, error: ${error}`));
```

but no difference
and this is the result of console.log of the first one

`Entered new beacons region! Object {minor: 0, major: 0, uuid: "region2", data: "id1: 523d3db0-0038-4cb4-b2b2-7d518adab463 id2: null id3: null"}`

and this is the result of console.log of the second one 

`Entered new beacons region! Object {minor: 0, major: 0, uuid: "region2", data: "id1: null id2: null id3: null"}`

**Comment by mmazzarolo** [comment]
Hello there!
First of all thank you for the info about the typo. I fixed it and I'll update the NPM release as soon as possible (I'm not on my personal pc right now).  
Regarding your issue I must admit that I worked more on the beacons ranging than on the beacons monitoring, but I'm planning to test it soon too (in two days from now I guess).  
If you catch the bug before me just send a pull request :)

**Comment by mmazzarolo** [comment]
Hey @RezaRahmati, any news on the bug?Did you try the last version of `react-native-beacons-android`?

**Comment by RezaRahmati** [comment]
@mmazzarolo Actually I start using ranging on beacons and I didn't check that

**Comment by RezaRahmati** [comment]
BTW we are using the latest version for our project :)

**Comment by mmazzarolo** [comment]
@RezaRahmati thanks for the info, I'll keep the issue open then :)

**Comment by sudharsan1988** [comment]
I am also having the same issue, I am getting 'Entered new beacons region!', { minor: 0, major: 0, uuid: 'REGION1' }

Here is my code,

`Beacons.detectIBeacons();

```
// Start detecting all iBeacons in the nearby
Beacons.startMonitoringForRegion('REGION1', 'B9407F30-F5F8-466E-AFF9-25556B57FE6D')
  .then(() => console.log('Beacons ranging started succesfully!'))
  .catch(error => console.log('Beacons ranging not started, error: ${error}'))

DeviceEventEmitter.addListener('regionDidEnter', (region) => {
  console.log('Entered new beacons region!', region) // Result of monitoring
})`
```

**Comment by mmazzarolo** [comment]
Since `react-native-beacons-android 2.0.0-beta.3` the output of the `regionDidEnter` event should be the same of `react-native-ibeacon`:

``` javascript
{
  region: String,
  uuid: String
}
```

I can't test it at the moment though...
