### ISSUE TITLE
I can not make it work for Eddystone

### ISSUE THREAD

**Issue by RezaRahmati** [mmazzarolo/react-native-beacons-android#8]
Hello

I have tried to make it work for Eddystone by the custom layout

I have tried these layouts and it beacons array in data is empty.

"s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19" from [this site](https://altbeacon.github.io/android-beacon-library/eddystone-how-to.html)

"s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19;d:20-21" from [https://github.com/RadiusNetworks/scanbeacon-gem/commit/8da479c0c03cbf7b1d90d45bc8a7734cabd38d46](url)

Do you have any idea why it doesn't show the beacons?

p.s The beeken app on android shows the Eddystone beacon in the same physical location.

**Comment by mmazzarolo** [comment]
Try adding all the following layouts: 
`"s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19"`
`"x,s:0-1=feaa,m:2-2=20,d:3-3,d:4-5,d:6-7,d:8-11,d:12-15"`
`"s:0-1=feaa,m:2-2=10,p:3-3:-41,i:4-20v"`

As you can see from [the `addParser` method on line 73](https://github.com/mmazzarolo/react-native-beacons-android/blob/master/android/src/main/java/com/mmazzarolo/beaconsandroid/BeaconsAndroidModule.java) I'm implementing the same method used in the [official documentation of altBeacons](https://altbeacon.github.io/android-beacon-library/eddystone-how-to.html).  
Let me know if it works!

**Comment by RezaRahmati** [comment]
First, thanks for fast response :)
Yes, I have tried to add all of them tough, but the same result, nothing is found
I thought you might have some clue about why it's not working

**Comment by mmazzarolo** [comment]
Unfortunately I don't have any EddyStone to test :(  
If you're interested you can debug the module by using the `adb logcat` command...
