### ISSUE TITLE
How can I change the interval of firing events?

### ISSUE THREAD

**Issue by RezaRahmati** [mmazzarolo/react-native-beacons-android#9]
Hi
Is There any way that I can change the interval of firing events (specially ranging)?

**Comment by mmazzarolo** [comment]
Hey!  
Take a look at [this (section _How do I customize the background scan rate?_)](https://altbeacon.github.io/android-beacon-library/battery_manager.html).  
Are you able to implement it by yourself?  
Otherwise I might expose that API if it is needed, let me know! :)

**Comment by RezaRahmati** [comment]
Hey

Thanks a lot, I will try to change that, but I would appreciate if you could make it in the API

**Comment by mmazzarolo** [comment]
Hey there, I just published a new release on npm (`1.2.1`):

```
* setForegroundScanPeriod(period): Sets the duration in milliseconds of each Bluetooth LE scan cycle to look for beacons (in foreground).
* setBackgroundScanPeriod(period): Sets the duration in milliseconds of each Bluetooth LE scan cycle to look for beacons (in background).
* setBackgroundBetweenScanPeriod(period): Sets the duration in milliseconds spent not scanning between each Bluetooth LE scan cycle when no ranging/monitoring clients are in the foreground.
```

They needs some testing though, I just tried succesfully the `setForegroundScanPeriod`.  
If you need any other method take [here](https://altbeacon.github.io/android-beacon-library/javadoc/index.html) you can find every method I can implement.  
You can easily implement them too! Just take a look at my last commit that shows what you should do (basically add the method decorated in `BeaconsAndroidModule.java` and implement the API to call in `index.js`).  
Pull requests are much appreciated 👍   

Let me know if I can close the issue.

**Comment by RezaRahmati** [comment]
Thanks, you are so fast man :)

**Comment by RezaRahmati** [comment]
I have test that, it works fine, thanks :)
:+1:
